[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.91.2'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'



[context.production]
[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.production.environment]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"