[build]
command = 'hugo'
publish = 'public'


[context]
[context.branch-deploy]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
ccommand = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.production]

[context.production.environment]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    


